In [2]:
import cv2
from PIL import Image
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import torch
import torch.nn.functional as F

In [3]:
def image_arrs(paths, im_arr):
    for path in paths:
        #read images, may need to change filepath
        image = cv2.imread('gtsrb-german-traffic-sign/'+path)
        image_from_array = Image.fromarray(image, 'RGB')
        #resize all images to 30x30
        size_image = image_from_array.resize((30, 30))
        #convert images to array
        image_arr = np.array(size_image.getdata(),
                        np.uint8).reshape(size_image.size[1], size_image.size[0], 3)
        im_arr.append(image_arr.flatten())
    return im_arr

In [4]:
df = pd.read_csv('gtsrb-german-traffic-sign/Train.csv')

In [5]:
paths1 = df[(df['ClassId']==1)]['Path'].values
paths2 = df[(df['ClassId']==2)]['Path'].values

In [6]:
class1_arrs = []
class1_arrs = image_arrs(paths1, class1_arrs)

class2_arrs = []
class2_arrs = image_arrs(paths2, class2_arrs)

In [7]:
X = class1_arrs + class2_arrs
y = len(class1_arrs)*[0] + len(class2_arrs)*[1]

In [8]:
#split data
X_train, X_test, y_train, y_test = train_test_split(
    np.array(X), np.array(y), test_size=0.2, random_state=0)

In [9]:
np.array(y)

array([0, 0, 0, ..., 1, 1, 1])

In [10]:
X_train = torch.from_numpy(X_train).float()
y_train = torch.from_numpy(y_train).float().view(-1, 1)
X_test = torch.from_numpy(X_test).float()
y_test = torch.from_numpy(y_test).float().view(-1, 1)

In [11]:
class LR_model(torch.nn.Module):
    def __init__(self):
        super(LR_model,self).__init__()
        self.linear = torch.nn.Linear(2700,1)
    def forward(self,x):
        y_pred = F.sigmoid(self.linear(x))
        return y_pred

In [12]:
lr_model = LR_model()
criterion = torch.nn.BCELoss(size_average = True)
optimizer = torch.optim.Adam(lr_model.parameters(),lr = 0.0001)

/anaconda3/lib/python3.7/site-packages/torch/nn/_reduction.py:43: UserWarning: size_average and reduce args will be deprecated, please use reduction='mean' instead.
  warnings.warn(warning.format(ret))


In [59]:
for epoch in range(1000):
    y_pred = lr_model(X_train)
    
    loss = criterion(y_pred, y_train)
    print(epoch, loss)
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

0 tensor(0.0959, grad_fn=<BinaryCrossEntropyBackward>)
1 tensor(0.0958, grad_fn=<BinaryCrossEntropyBackward>)
2 tensor(0.0958, grad_fn=<BinaryCrossEntropyBackward>)
3 tensor(0.0957, grad_fn=<BinaryCrossEntropyBackward>)
4 tensor(0.0957, grad_fn=<BinaryCrossEntropyBackward>)
5 tensor(0.0956, grad_fn=<BinaryCrossEntropyBackward>)
6 tensor(0.0956, grad_fn=<BinaryCrossEntropyBackward>)
7 tensor(0.0955, grad_fn=<BinaryCrossEntropyBackward>)
8 tensor(0.0954, grad_fn=<BinaryCrossEntropyBackward>)
9 tensor(0.0954, grad_fn=<BinaryCrossEntropyBackward>)
10 tensor(0.0953, grad_fn=<BinaryCrossEntropyBackward>)
11 tensor(0.0953, grad_fn=<BinaryCrossEntropyBackward>)
12 tensor(0.0952, grad_fn=<BinaryCrossEntropyBackward>)
13 tensor(0.0952, grad_fn=<BinaryCrossEntropyBackward>)
14 tensor(0.0951, grad_fn=<BinaryCrossEntropyBackward>)
15 tensor(0.0951, grad_fn=<BinaryCrossEntropyBackward>)
16 tensor(0.0950, grad_fn=<BinaryCrossEntropyBackward>)
17 tensor(0.0950, grad_fn=<BinaryCrossEntropyBackward>)
18

169 tensor(0.0885, grad_fn=<BinaryCrossEntropyBackward>)
170 tensor(0.0885, grad_fn=<BinaryCrossEntropyBackward>)
171 tensor(0.0884, grad_fn=<BinaryCrossEntropyBackward>)
172 tensor(0.0884, grad_fn=<BinaryCrossEntropyBackward>)
173 tensor(0.0883, grad_fn=<BinaryCrossEntropyBackward>)
174 tensor(0.0883, grad_fn=<BinaryCrossEntropyBackward>)
175 tensor(0.0883, grad_fn=<BinaryCrossEntropyBackward>)
176 tensor(0.0882, grad_fn=<BinaryCrossEntropyBackward>)
177 tensor(0.0882, grad_fn=<BinaryCrossEntropyBackward>)
178 tensor(0.0882, grad_fn=<BinaryCrossEntropyBackward>)
179 tensor(0.0881, grad_fn=<BinaryCrossEntropyBackward>)
180 tensor(0.0881, grad_fn=<BinaryCrossEntropyBackward>)
181 tensor(0.0881, grad_fn=<BinaryCrossEntropyBackward>)
182 tensor(0.0880, grad_fn=<BinaryCrossEntropyBackward>)
183 tensor(0.0880, grad_fn=<BinaryCrossEntropyBackward>)
184 tensor(0.0880, grad_fn=<BinaryCrossEntropyBackward>)
185 tensor(0.0879, grad_fn=<BinaryCrossEntropyBackward>)
186 tensor(0.0879, grad_fn=<Bin

327 tensor(0.0834, grad_fn=<BinaryCrossEntropyBackward>)
328 tensor(0.0833, grad_fn=<BinaryCrossEntropyBackward>)
329 tensor(0.0833, grad_fn=<BinaryCrossEntropyBackward>)
330 tensor(0.0833, grad_fn=<BinaryCrossEntropyBackward>)
331 tensor(0.0832, grad_fn=<BinaryCrossEntropyBackward>)
332 tensor(0.0832, grad_fn=<BinaryCrossEntropyBackward>)
333 tensor(0.0832, grad_fn=<BinaryCrossEntropyBackward>)
334 tensor(0.0832, grad_fn=<BinaryCrossEntropyBackward>)
335 tensor(0.0831, grad_fn=<BinaryCrossEntropyBackward>)
336 tensor(0.0831, grad_fn=<BinaryCrossEntropyBackward>)
337 tensor(0.0831, grad_fn=<BinaryCrossEntropyBackward>)
338 tensor(0.0830, grad_fn=<BinaryCrossEntropyBackward>)
339 tensor(0.0830, grad_fn=<BinaryCrossEntropyBackward>)
340 tensor(0.0830, grad_fn=<BinaryCrossEntropyBackward>)
341 tensor(0.0830, grad_fn=<BinaryCrossEntropyBackward>)
342 tensor(0.0829, grad_fn=<BinaryCrossEntropyBackward>)
343 tensor(0.0829, grad_fn=<BinaryCrossEntropyBackward>)
344 tensor(0.0829, grad_fn=<Bin

471 tensor(0.0796, grad_fn=<BinaryCrossEntropyBackward>)
472 tensor(0.0796, grad_fn=<BinaryCrossEntropyBackward>)
473 tensor(0.0795, grad_fn=<BinaryCrossEntropyBackward>)
474 tensor(0.0795, grad_fn=<BinaryCrossEntropyBackward>)
475 tensor(0.0795, grad_fn=<BinaryCrossEntropyBackward>)
476 tensor(0.0795, grad_fn=<BinaryCrossEntropyBackward>)
477 tensor(0.0795, grad_fn=<BinaryCrossEntropyBackward>)
478 tensor(0.0794, grad_fn=<BinaryCrossEntropyBackward>)
479 tensor(0.0794, grad_fn=<BinaryCrossEntropyBackward>)
480 tensor(0.0794, grad_fn=<BinaryCrossEntropyBackward>)
481 tensor(0.0794, grad_fn=<BinaryCrossEntropyBackward>)
482 tensor(0.0793, grad_fn=<BinaryCrossEntropyBackward>)
483 tensor(0.0793, grad_fn=<BinaryCrossEntropyBackward>)
484 tensor(0.0793, grad_fn=<BinaryCrossEntropyBackward>)
485 tensor(0.0793, grad_fn=<BinaryCrossEntropyBackward>)
486 tensor(0.0792, grad_fn=<BinaryCrossEntropyBackward>)
487 tensor(0.0792, grad_fn=<BinaryCrossEntropyBackward>)
488 tensor(0.0792, grad_fn=<Bin

624 tensor(0.0763, grad_fn=<BinaryCrossEntropyBackward>)
625 tensor(0.0763, grad_fn=<BinaryCrossEntropyBackward>)
626 tensor(0.0763, grad_fn=<BinaryCrossEntropyBackward>)
627 tensor(0.0763, grad_fn=<BinaryCrossEntropyBackward>)
628 tensor(0.0762, grad_fn=<BinaryCrossEntropyBackward>)
629 tensor(0.0762, grad_fn=<BinaryCrossEntropyBackward>)
630 tensor(0.0762, grad_fn=<BinaryCrossEntropyBackward>)
631 tensor(0.0762, grad_fn=<BinaryCrossEntropyBackward>)
632 tensor(0.0762, grad_fn=<BinaryCrossEntropyBackward>)
633 tensor(0.0761, grad_fn=<BinaryCrossEntropyBackward>)
634 tensor(0.0761, grad_fn=<BinaryCrossEntropyBackward>)
635 tensor(0.0761, grad_fn=<BinaryCrossEntropyBackward>)
636 tensor(0.0761, grad_fn=<BinaryCrossEntropyBackward>)
637 tensor(0.0761, grad_fn=<BinaryCrossEntropyBackward>)
638 tensor(0.0761, grad_fn=<BinaryCrossEntropyBackward>)
639 tensor(0.0760, grad_fn=<BinaryCrossEntropyBackward>)
640 tensor(0.0760, grad_fn=<BinaryCrossEntropyBackward>)
641 tensor(0.0760, grad_fn=<Bin

781 tensor(0.0736, grad_fn=<BinaryCrossEntropyBackward>)
782 tensor(0.0735, grad_fn=<BinaryCrossEntropyBackward>)
783 tensor(0.0735, grad_fn=<BinaryCrossEntropyBackward>)
784 tensor(0.0735, grad_fn=<BinaryCrossEntropyBackward>)
785 tensor(0.0735, grad_fn=<BinaryCrossEntropyBackward>)
786 tensor(0.0735, grad_fn=<BinaryCrossEntropyBackward>)
787 tensor(0.0735, grad_fn=<BinaryCrossEntropyBackward>)
788 tensor(0.0735, grad_fn=<BinaryCrossEntropyBackward>)
789 tensor(0.0734, grad_fn=<BinaryCrossEntropyBackward>)
790 tensor(0.0734, grad_fn=<BinaryCrossEntropyBackward>)
791 tensor(0.0734, grad_fn=<BinaryCrossEntropyBackward>)
792 tensor(0.0734, grad_fn=<BinaryCrossEntropyBackward>)
793 tensor(0.0734, grad_fn=<BinaryCrossEntropyBackward>)
794 tensor(0.0734, grad_fn=<BinaryCrossEntropyBackward>)
795 tensor(0.0733, grad_fn=<BinaryCrossEntropyBackward>)
796 tensor(0.0733, grad_fn=<BinaryCrossEntropyBackward>)
797 tensor(0.0733, grad_fn=<BinaryCrossEntropyBackward>)
798 tensor(0.0733, grad_fn=<Bin

927 tensor(0.0714, grad_fn=<BinaryCrossEntropyBackward>)
928 tensor(0.0714, grad_fn=<BinaryCrossEntropyBackward>)
929 tensor(0.0714, grad_fn=<BinaryCrossEntropyBackward>)
930 tensor(0.0714, grad_fn=<BinaryCrossEntropyBackward>)
931 tensor(0.0714, grad_fn=<BinaryCrossEntropyBackward>)
932 tensor(0.0713, grad_fn=<BinaryCrossEntropyBackward>)
933 tensor(0.0713, grad_fn=<BinaryCrossEntropyBackward>)
934 tensor(0.0713, grad_fn=<BinaryCrossEntropyBackward>)
935 tensor(0.0713, grad_fn=<BinaryCrossEntropyBackward>)
936 tensor(0.0713, grad_fn=<BinaryCrossEntropyBackward>)
937 tensor(0.0713, grad_fn=<BinaryCrossEntropyBackward>)
938 tensor(0.0713, grad_fn=<BinaryCrossEntropyBackward>)
939 tensor(0.0712, grad_fn=<BinaryCrossEntropyBackward>)
940 tensor(0.0712, grad_fn=<BinaryCrossEntropyBackward>)
941 tensor(0.0712, grad_fn=<BinaryCrossEntropyBackward>)
942 tensor(0.0712, grad_fn=<BinaryCrossEntropyBackward>)
943 tensor(0.0712, grad_fn=<BinaryCrossEntropyBackward>)
944 tensor(0.0712, grad_fn=<Bin

In [13]:
lr_model(X_train)

/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:1351: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")


tensor([[1.0000e+00],
        [1.9570e-26],
        [3.2160e-16],
        ...,
        [1.0000e+00],
        [1.0000e+00],
        [4.9485e-24]], grad_fn=<SigmoidBackward>)

tensor([[1.],
        [0.],
        [0.],
        ...,
        [0.],
        [1.],
        [1.]])